service: sbcourses-course-info

plugins:
  - serverless-functions-base-path
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stage: ${opt:stage, "dev"}
  apiGateway:
    restApiId: !ImportValue sbcourses-${self:provider.stage}-api-id
    restApiRootResourceId: !ImportValue sbcourses-${self:provider.stage}-resource-id
  environment:
    UCSB_API_KEY: ${ssm:sbcourses-consumer-key}
    UCSB_API_SECRET: ${ssm:sbcourses-consumer-secret}

functions:
  search:
    handler: search.handler
    events:
      - http:
          method: get
          path: courses/search
          cors: true
  currentQuarter:
    handler: currentQuarter.handler
    events:
      - http:
          method: get
          path: currentQuarter
          cors: true

custom:
  functionsBasePath: src/functions
